version: "3.7"
services:
  converter:
    build:
      dockerfile: Dockerfile
      context: .
    command: ["-o", "database", "-c", "mysql://root:example@mysql:3306/test"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
